config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  hammond:
    dotfiles:
    - f_zshrc
    - d_i3
